export default {
  player: { type: 'id', ref: 'Player' },
  league: { type: 'id', ref: 'League' },
  season: {type: 'id', ref: 'Season'},
  division: { type: 'id', ref: 'Division' },
  team: { type: 'id', ref: 'Team' },
  vsTeam: { type: 'id', ref: 'Team' },
  game: { type: 'id', ref: 'Game' },
  points: {type: Number, default: -1},
  assists: {type: Number, default: -1},
  offensiveRebounds: {type: Number, default: -1},
  defensiveRebounds: {type: Number, default: -1},
  totalRebounds: {type: Number, default: -1},
  steals: {type: Number, default: -1},
  blocks: {type: Number, default: -1},
  fieldGoalsAttempted: {type: Number, default: -1},
  fieldGoalsMade: {type: Number, default: -1},
  threePointsAttempted: {type: Number, default: -1},
  threePointsMade: {type: Number, default: -1},
  freeThrowsAttempted: {type: Number, default: -1},
  freeThrowsMade: {type: Number, default: -1},
  fouls: {type: Number, default: -1},
  turnovers: {type: Number, default: -1},
  created: { type: Date, default: Date.now },
  updated: { type: Date, default: Date.now }
};
